### PR TITLE
Implemented Audit annotations for the `ShoppingList` entity

### LINKED ISSUE #23: Audit annotations for the "ShoppingList" entity
> [!IMPORTANT]
> Read issue #2 first

Implement the use of `@CreatedDate` and `@LastModifiedDate` annotations in the [`ShoppingList`](https://github.com/despensa-app/despensa-rest-api/blob/450c0ec47c199c81d87a56f8f336bb6b605e6c18/src/main/java/dev/nmarulo/depensaapp/app/shoppinglist/ShoppingList.java) entity, in the `createdAt` and `updatedAt` fields respectively.

Remove the lines of code where these dates are set manually.

Doc: https://docs.spring.io/spring-data/rest/reference/data-commons/auditing.html

### PR DESCRIPTION
**Pull request by JinnJarBurger**
Fixes #23 

**Description**

Implemented Audit annotations for the `ShoppingList` entity.

**Screenshots**

### CODE REVIEW

**Comment by JinnJarBurger** [comment]
Hello @nmarulo , could you please have a look at this PR and let me know if everything's all good? Thanks!

**Comment by nmarulo** [comment]
@JinnJarBurger I have checked it and everything works correctly.

Please, you can leave a more extensive description in the first comment or brief, but comment the reason for the changes made.

Even if I merge it, please update the description.

Thank you.

**Comment by JinnJarBurger** [comment]
> @JinnJarBurger I have checked it and everything works correctly.
> 
> Please, you can leave a more extensive description in the first comment or brief, but comment the reason for the changes made.
> 
> Even if I merge it, please update the description.
> 
> Thank you.

sure, on it.

**Comment by JinnJarBurger** [comment]
> > @JinnJarBurger I have checked it and everything works correctly.
> > Please, you can leave a more extensive description in the first comment or brief, but comment the reason for the changes made.
> > Even if I merge it, please update the description.
> > Thank you.
> 
> sure, on it.

@nmarulo the description has been updated accordingly.

**Comment by nmarulo** [comment]
@JinnJarBurger Thanks

**Pull request merged**
