### PR TITLE
Implemented randomBigDecimal method

### PR DESCRIPTION
**Pull request by KaroK365**
Fixes #

Create "randomBigDecimal" method #35

**Description**

Implemented the randomBigDecimal method which generates random big decimal numbers between 1 and 1000, then used it in "src/test/java/dev/nmarulo/depensaapp/app/products/ProductServiceTestUtil.java" and "src/test/java/dev/nmarulo/depensaapp/app/shoppinglist/ShoppingListServiceTestUtil.java" to generate random Prices and Calories.

Also removed "import java.time.LocalDateTime" as i did not notice it being used.

### CODE REVIEW

**Comment by nmarulo** [comment]
Thank you for the PR 😄.

The solution is valid but the result is not limited to two decimal places. Example of the actual implementation: `243.94340437692452`

Although, my intention was to use the datafaker library, if possible.

I see that I left the link to the providers page and the one to use is here: [datafaker number](https://javadoc.io/doc/net.datafaker/datafaker/latest/net/datafaker/providers/base/Number.html)

**Comment by KaroK365** [comment]
I will try implementing the datafaker library and i have to limit the decimal places upto two places right?

**Comment by KaroK365** [comment]
I will make a new pull request for the changes you specified so may I close this request?

**Comment by nmarulo** [comment]
If you make the changes in the same branch, the result appears here. It is not necessary to create another PR.

**Comment by KaroK365** [comment]
oh ok thanks for letting me know , I am new to this.

**Comment by KaroK365** [comment]
I implemented the change.

**Comment by nmarulo** [comment]
@KaroK365 Thanks 😊

**Pull request merged**
