### PR TITLE
fix: update type in Users database to Long (#8)

### LINKED ISSUE #8: Update type in Users database
> [!IMPORTANT]
> Read issue #2 first

Change the type from `Integer` to `Long` on [line 25](https://github.com/despensa-app/despensa-rest-api/blob/1805ef7f4331b77bb8a50d48f5290d4684e2f161/src/main/java/dev/nmarulo/depensaapp/app/users/User.java#L25) of the `Users` class.

As in issue #7, this change will cause the application to no longer compile with maven, because you have to update all classes related to the `Users` entity ID field.

<details>
<summary>List of classes to be modified</summary>

image

</details>

Finally, in the SQL script `schema.sql` change the type to `BIGINT` on [line 39](https://github.com/despensa-app/despensa-rest-api/blob/1805ef7f4331b77bb8a50d48f5290d4684e2f161/src/main/resources/db/schema.sql#L39) and [line 62](https://github.com/despensa-app/despensa-rest-api/blob/1805ef7f4331b77bb8a50d48f5290d4684e2f161/src/main/resources/db/schema.sql#L62).

> [!NOTE]
> The following script is a note to myself, so you can ignore it.

<details>
<summary>Script a ejecutar en la base de datos de demo</summary>

```sql
ALTER TABLE shopping_list
    DROP FOREIGN KEY fk_shopping_list_users1;
ALTER TABLE shopping_list
    MODIFY user_id BIGINT;
ALTER TABLE users
    MODIFY id BIGINT AUTO_INCREMENT;
ALTER TABLE shopping_list
    ADD CONSTRAINT `fk_shopping_list_users1`
        FOREIGN KEY (`user_id`)
            REFERENCES `users` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION;
```

</summary>

### PR DESCRIPTION
**Pull request by gitclonegaurang**
Fixes #8

**Description**
This commit updates the `id` field in the `Users` entity from `Integer` to `Long` . 
As a result, all related classes interacting with the `Users` entity have been updated to reflect this change. The SQL script (`schema.sql`) has also been modified to change the corresponding type from `INT` to `BIGINT` on lines 39 and 62, ensuring that the database schema matches the updated code.

### CODE REVIEW

**Comment by gitclonegaurang** [comment]
@nmarulo I have updated the type to Long for `id` but now `AuthenticationService.java` is expecting Integer instead of Long if you could guide me on this should i change into Long for AuthenticationService or just change the returned Long into Integer.
If you could please guide me on this.

**Comment by nmarulo** [comment]
> @nmarulo I have updated the type to Long for `id` but now `AuthenticationService.java` is expecting Integer instead of Long if you could guide me on this should i change into Long for AuthenticationService or just change the returned Long into Integer. If you could please guide me on this.

@gitclonegaurang 
Sure, no problem. What happens, is that, I believe that not seen the image with the classes that I indicate 😅, it is necessary to change these classes:

issue-8

Everything that is related to the Id of the entity users.

**Comment by gitclonegaurang** [comment]
I will update the changes.

**Comment by nmarulo** [comment]
Thanks @gitclonegaurang

**Pull request merged**
