### PR TITLE
Issue7

### LINKED ISSUE #7: Update type in Product database
> [!IMPORTANT]
> Read issue #2 first

Change the type from `Integer` to `Long` on [line 28](https://github.com/despensa-app/despensa-rest-api/blob/1805ef7f4331b77bb8a50d48f5290d4684e2f161/src/main/java/dev/nmarulo/depensaapp/app/products/Product.java#L28) of the `Product` class.

This change will cause the application to no longer compile with maven, because you have to update all classes related to the `Product` entity ID field.

<details>
<summary>List of classes to be modified</summary>

image

</details>

Finally, in the SQL script `schema.sql` change the type to `BIGINT` on [line 20](https://github.com/despensa-app/despensa-rest-api/blob/1805ef7f4331b77bb8a50d48f5290d4684e2f161/src/main/resources/db/schema.sql#L20) and [line 97](https://github.com/despensa-app/despensa-rest-api/blob/1805ef7f4331b77bb8a50d48f5290d4684e2f161/src/main/resources/db/schema.sql#L97).

> [!NOTE]
> The following script is a note to myself, so you can ignore it.

<details>
<summary>Script a ejecutar en la base de datos de demo</summary>

```sql
ALTER TABLE products_has_shopping_list
    DROP FOREIGN KEY fk_products_has_shopping_list_products;
ALTER TABLE products_has_shopping_list
    MODIFY product_id BIGINT;
ALTER TABLE products
    MODIFY id BIGINT AUTO_INCREMENT;
ALTER TABLE products_has_shopping_list
    ADD CONSTRAINT `fk_products_has_shopping_list_products`
        FOREIGN KEY (`product_id`)
            REFERENCES `products` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION;
```

</summary>

### PR DESCRIPTION
**Pull request by Sofiyan-coder**
Fixes #7

**Description**

Change the type from  <mark>Integer</mark>  to  <mark>Long</mark>  on  [line 28](https://github.com/despensa-app/despensa-rest-api/blob/1805ef7f4331b77bb8a50d48f5290d4684e2f161/src/main/java/dev/nmarulo/depensaapp/app/products/Product.java#L28) of the  <mark>Product</mark>  class.
<br>
This change will cause the application to no longer compile with maven, because you have to update all classes related to the  <mark>Product</mark>  entity ID field.
<br>
<details>
<summary>List of Classes needed to Modified</summary>
 
image

</details>

Finally, in the SQL script  <mark>schema.sql</mark>  change the type to  <mark>BIGINT</mark>  on [line 20](https://github.com/despensa-app/despensa-rest-api/blob/1805ef7f4331b77bb8a50d48f5290d4684e2f161/src/main/resources/db/schema.sql#L20) and [line 97](https://github.com/despensa-app/despensa-rest-api/blob/1805ef7f4331b77bb8a50d48f5290d4684e2f161/src/main/resources/db/schema.sql#L97).
<br>

### CODE REVIEW

**Comment by nmarulo** [comment]
@Sofiyan-coder Please check the compilation process, because it has failed.

The problem may be `ShoppingListController.java`.

https://github.com/despensa-app/despensa-rest-api/actions/runs/11132954558/job/30939121344

**Comment by Sofiyan-coder** [comment]
ok I will take a look at it and Update you

**Comment by Sofiyan-coder** [comment]
@nmarulo  I tried one last time. Please check now to see if the error occurs again. I can understand your actions regarding this issue #7

Thank you

**Comment by Sofiyan-coder** [comment]
@nmarulo  is it working now?

**Comment by nmarulo** [comment]
@Sofiyan-coder Thanks

**Pull request merged**
